/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GameService } from "../game.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { GameCreateInput } from "./GameCreateInput";
import { GameWhereInput } from "./GameWhereInput";
import { GameWhereUniqueInput } from "./GameWhereUniqueInput";
import { GameFindManyArgs } from "./GameFindManyArgs";
import { GameUpdateInput } from "./GameUpdateInput";
import { Game } from "./Game";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class GameControllerBase {
  constructor(
    protected readonly service: GameService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Game",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Game })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(@common.Body() data: GameCreateInput): Promise<Game> {
    return await this.service.create({
      data: {
        ...data,

        description: data.description
          ? {
              connect: data.description,
            }
          : undefined,
      },
      select: {
        active: true,
        coverImage: true,
        createdAt: true,

        description: {
          select: {
            id: true,
          },
        },

        developer: true,
        favoriteCount: true,
        gametype: true,
        id: true,
        multiplayer: true,
        timesPlayed: true,
        title: true,
        totalIn: true,
        totalOut: true,
        updatedAt: true,
        websiteCategory: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Game",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Game] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(GameFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Game[]> {
    const args = plainToClass(GameFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        active: true,
        coverImage: true,
        createdAt: true,

        description: {
          select: {
            id: true,
          },
        },

        developer: true,
        favoriteCount: true,
        gametype: true,
        id: true,
        multiplayer: true,
        timesPlayed: true,
        title: true,
        totalIn: true,
        totalOut: true,
        updatedAt: true,
        websiteCategory: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Game",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Game })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: GameWhereUniqueInput
  ): Promise<Game | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        active: true,
        coverImage: true,
        createdAt: true,

        description: {
          select: {
            id: true,
          },
        },

        developer: true,
        favoriteCount: true,
        gametype: true,
        id: true,
        multiplayer: true,
        timesPlayed: true,
        title: true,
        totalIn: true,
        totalOut: true,
        updatedAt: true,
        websiteCategory: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Game",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Game })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: GameWhereUniqueInput,
    @common.Body() data: GameUpdateInput
  ): Promise<Game | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          description: data.description
            ? {
                connect: data.description,
              }
            : undefined,
        },
        select: {
          active: true,
          coverImage: true,
          createdAt: true,

          description: {
            select: {
              id: true,
            },
          },

          developer: true,
          favoriteCount: true,
          gametype: true,
          id: true,
          multiplayer: true,
          timesPlayed: true,
          title: true,
          totalIn: true,
          totalOut: true,
          updatedAt: true,
          websiteCategory: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Game",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Game })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: GameWhereUniqueInput
  ): Promise<Game | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          active: true,
          coverImage: true,
          createdAt: true,

          description: {
            select: {
              id: true,
            },
          },

          developer: true,
          favoriteCount: true,
          gametype: true,
          id: true,
          multiplayer: true,
          timesPlayed: true,
          title: true,
          totalIn: true,
          totalOut: true,
          updatedAt: true,
          websiteCategory: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
